### ISSUE TITLE
CHTHON is not defined 

### ISSUE THREAD

**Issue by zubaira123** [Andrey1994/brainapps#1]
self.board_id = CYTHON.board_id
NameError: name 'CYTHON' is not defined

**Comment by Andrey1994** [comment]
CYTHON was a typo correct name is CYTON, I've fixed it in brainflow but forgot to fix it here. I will rename it in brainapps as well
Also you can checkout previous version of branflow\brainapps(the latest tag for example) or just replace CYTHON by CYTON by yourself

**Comment by Andrey1994** [comment]
fixed, also I've updated project to use python3 instead 2.7

**Comment by zubaira123** [comment]
Thank you so much.

**Comment by Hfut-Lujie** [comment]
self.board_id = CYTON.board_id. But still error.
![QQ20191109-171336](https://user-images.githubusercontent.com/49814550/68526220-7a0b1f80-0314-11ea-97b3-21e4b663a2a0.png)

**Comment by Andrey1994** [comment]
I am aware it, during last couple of months brainflow API was changed significantly and I had no time to update this project to use new API

**Comment by Andrey1994** [comment]
I am working on new brainflow based speller with one big company and it will replace this one soon

**Comment by Hfut-Lujie** [comment]
Wow, that's cool! Looking forward to it.&nbsp;Thanks for your efforts.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Andrey Parfenov"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月9日(星期六) 晚上7:33
收件人:&nbsp;"Andrey1994/brainapps"<brainapps@noreply.github.com&gt;;
抄送:&nbsp;"1215725271"<1215725271@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Andrey1994/brainapps] CHTHON is not defined  (#1)




I am working on new brainflow based speller with one big company and it will replace this one soon
