### ISSUE TITLE
invalid board

### ISSUE THREAD

**Issue by zubaira123** [Andrey1994/brainapps#3]
Im using cyton board still im facing this issue
File "C:/Users/Dell/PycharmProjects/p300/brainapps-master/brainapps-master/p300-speller/classifier.py", line 269, in main
    data_x, data_y = prepare_data (eeg_data, event_data, settings)
  File "C:/Users/Dell/PycharmProjects/p300/brainapps-master/brainapps-master/p300-speller/classifier.py", line 74, in prepare_data
    raise ValueError ('invalid board')
ValueError: invalid board

**Comment by Andrey1994** [comment]
```
if settings['general']['board'] == 'Cyton':

num_datapoints = int (CYTON.fs_hz * (stop_time - start_time))

else:

raise ValueError ('invalid board')

```
Please check settings file which you use

**Comment by zubaira123** [comment]
FutureWarning: 'select' is deprecated and will be removed in a future release. You can use .loc[labels.map(crit)] as a replacement
  event_eeg_data = event_eeg_data.select (lambda col: col.startswith ('eeg'), axis = 1)

how can i fix this ?

**Comment by zubaira123** [comment]
when I am training it on new subject and data files change it gives me error in classify lda and on data_X and data_Y. 
if i added 1 previous file and then new data files it work properly and classify generate pkl files.

**Comment by Andrey1994** [comment]
Could you add error message?
By default classifier looks for all files with prefixes like eeg_*.csv events_*.csv https://github.com/Andrey1994/brainapps/blob/master/p300-speller/classifier.py#L245 you can override this behavior using cmd args

**Comment by zubaira123** [comment]
File
"C:/Users/DELL/PycharmProjects/p300_brl/brainapps-master/brainapps-master/p300-speller/classifier.py",
line 290, in <module>
    main ()
  File
"C:/Users/DELL/PycharmProjects/p300_brl/brainapps-master/brainapps-master/p300-speller/classifier.py",
line 286, in main
    classify_lda (data_x, data_y, settings)
  File
"C:/Users/DELL/PycharmProjects/p300_brl/brainapps-master/brainapps-master/p300-speller/classifier.py",
line 121, in classify_lda
    pca.fit (x_train, y_train)
  File
"C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\decomposition\pca.py",
line 341, in fit
    self._fit(X)
  File
"C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\decomposition\pca.py",
line 407, in _fit
    return self._fit_full(X, n_components)
  File
"C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\decomposition\pca.py",
line 426, in _fit_full
    % (n_components, min(n_samples, n_features)))
ValueError: n_components=800 must be between 0 and min(n_samples,
n_features)=174 with svd_solver='full'

**Comment by Andrey1994** [comment]
seems like there are too few data in your file, number of features should be smth like: 

number_of_eeg_channels(8) * Cyton_sampling_rate(250) * eeg_end(here https://github.com/Andrey1994/brainapps/blob/master/p300-speller/ui_settings.yml#L6 it's 850) / 1000 it's approximately 1600 and PCA should decrease this amount of features by two times.

And in your file number of features is 174 instead ~1600

**Comment by Andrey1994** [comment]
I can take a look if you send eeg and event files

**Comment by Andrey1994** [comment]
174 looks like it was not multiplied by number of channels

**Comment by zubaira123** [comment]
okay let me share data files with you.

**Comment by Andrey1994** [comment]
You can use git lfs or google drive my email is a1994ndrey@gmail.com

**Comment by zubaira123** [comment]
data files sent!

**Comment by Andrey1994** [comment]
in PCA valid number of components is a value between 0 and min(n_samples, n_features) if you use only this single file number of samples is 700 and number of features is 1496, so PCA with 800 components doesnt fit this requirement for a single file.

You can try to add more data files or decrease number of PCA components to smth lower that 700
